[workspace]
name = "CAD+"
version = "0.1.0"
description = "Aplicación CAD en C++20 con SFML"
authors = ["Hernani <afhernani@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]
build = "cmake -B build -G \"Visual Studio 16 2019\" -A x64 && cmake --build build --config Release"
dev = { cmd = "cmake --build build --config Release && ./build/Release/CAD+.exe", depends-on = ["build"] }
run = "./build/Release/CAD+"

[activation.env]
CMAKE_GENERATOR = "Visual Studio 16 2019"

[dependencies]
cxx-compiler = ">=1.7.0"
cmake = ">=3.28.0"
sfml = "2.6.*"
